=== jgiovaresco/my-resume/xml/resume.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.giovaresco.fr/resume"
		xmlns:tns="http://www.giovaresco.fr/resume"
		elementFormDefault="qualified">

	<element name="resume" type="tns:ResumeType"/>

	<complexType name="ResumeType">
		<annotation>
			<documentation>Defines a resume</documentation>
		</annotation>
		<sequence>
			<element name="personal" type="tns:PersonalType"/>
			<element name="title" type="tns:TitleType"/>
			<element name="educations">
				<complexType>
					<sequence>
						<element name="education" type="tns:EducationType" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="trainings">
				<complexType>
					<sequence>
						<element name="training" type="tns:TrainingType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="experiences">
				<complexType>
					<sequence>
						<element name="experience" type="tns:ExperienceType" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="skills">
				<complexType>
					<sequence>
						<element name="skill" type="tns:SkillType" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element ref="tns:hobbies"/>
			<element name="languages">
				<complexType>
					<sequence>
						<element name="language" type="tns:LanguageType" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="PersonalType">
		<annotation>
			<documentation>Defines the personal information</documentation>
		</annotation>
		<sequence>
			<element name="firstname" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="lastname" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="address" type="tns:AddressType" minOccurs="1" maxOccurs="1"/>
			<element name="phone" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="mobile" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="email" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="email_www" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="webAddress">
				<complexType>
					<sequence>
						<element name="www" type="tns:WebType" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
			<element name="comment" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="WebType">
		<annotation>
			<documentation>Defines a web address</documentation>
		</annotation>
		<attribute name="type">
			<simpleType>
				<restriction base="string">
					<enumeration value="homepage"/>
					<enumeration value="github"/>
					<enumeration value="linkedin"/>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="url" type="string"/>
		<attribute name="name" type="string"/>
	</complexType>

	<complexType name="AddressType">
		<annotation>
			<documentation>Defines an address</documentation>
		</annotation>
		<sequence>
			<element name="street" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="zipcode" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="city" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="country" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="TitleType">
		<annotation>
			<documentation>Defines the title of the resume</documentation>
		</annotation>
		<sequence>
			<element name="profession" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="presentation" type="tns:PresentationType" minOccurs="0" maxOccurs="1"/>
			<element name="speciality" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="PresentationType" mixed="true">
		<sequence>
			<element name="newline" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>

	<complexType name="EducationType">
		<annotation>
			<documentation>Defines an education entry</documentation>
		</annotation>
		<sequence>
			<element name="year" type="string" minOccurs="1" maxOccurs="1"/>
			<element name="certificate" type="string"/>
			<element name="speciality" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="school" type="tns:OrganizationType"/>
		</sequence>
	</complexType>

	<complexType name="OrganizationType">
		<annotation>
			<documentation>Defines an organization (school, company, ...)</documentation>
		</annotation>
		<sequence>
			<element name="title" type="string"/>
			<element name="www" type="string"/>
			<element name="city" type="string" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="ExperienceType">
		<annotation>
			<documentation>Defines a job experience</documentation>
		</annotation>
		<sequence>
			<element name="year" type="string"/>
			<element name="title" type="string"/>
			<element name="company" type="tns:OrganizationType"/>
			<element name="description" type="tns:DetailType" minOccurs="0" />
			<element name="missions">
				<complexType>
					<sequence>
						<element name="mission" type="tns:MissionType" minOccurs="1" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="MissionType">
		<annotation>
			<documentation>Defines a mission</documentation>
		</annotation>
		<sequence>
			<element name="title" type="string"/>
			<element name="competences" type="string"/>
			<element name="responsibility" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="detail" type="tns:DetailType" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="DetailType" mixed="true">
		<sequence>
			<element name="newline" minOccurs="0" maxOccurs="unbounded"/>
			<element name="list" minOccurs="0" maxOccurs="unbounded">
				<complexType>
					<sequence>
						<element name="item" minOccurs="0" maxOccurs="unbounded"/>
					</sequence>
				</complexType>
			</element>
		</sequence>
	</complexType>

	<complexType name="SkillType">
		<annotation>
			<documentation>Defines a skill</documentation>
		</annotation>
		<sequence>
			<element name="type" type="string"/>
			<element name="value" type="string"/>
		</sequence>
	</complexType>

	<complexType name="TrainingType">
		<annotation>
			<documentation>Defines a training</documentation>
		</annotation>
		<sequence>
			<element name="year" type="string"/>
			<element name="title" type="string"/>
			<element name="description" type="string" minOccurs="0" maxOccurs="1"/>
			<element name="organization" type="tns:OrganizationType" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="LanguageType">
		<annotation>
			<documentation>Defines a language</documentation>
		</annotation>
		<sequence>
			<element name="name" type="string"/>
			<element name="level" type="string"/>
		</sequence>
	</complexType>

	<!-- Hobbies -->
	<element name="hobbies">
		<annotation>
			<documentation>Defines the hobbies</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element name="hobby" type="string" maxOccurs="unbounded"/>
			</sequence>
		</complexType>
	</element>
</schema>

=== jgiovaresco/my-resume/xml/resume_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<resume xmlns="http://www.giovaresco.fr/resume" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.giovaresco.fr/resume resume.xsd ">
	<personal>
		<firstname>Julien</firstname>
		<lastname>Giovaresco</lastname>
		<address>
			<street>16 rue Saint Exupéry</street>
			<zipcode>38400</zipcode>
			<city>Saint Martin d'Hères</city>
			<country>France</country>
		</address>
		<mobile>+336 26 48 84 39</mobile>
		<email>julien@giovaresco.fr</email>
		<email_www>contactme@giovaresco.fr</email_www>
		<webAddress>
			<www name="julien.giovaresco.fr" type="homepage" url="julien.giovaresco.fr"/>
			<www name="Github" type="github" url="www.github.com/jgiovaresco"/>
			<www name="LinkedIn" type="linkedin" url="www.linkedin.com/in/jgiovaresco"/>
		</webAddress>
		<comment>Single - 33 years old - Driving licence</comment>
	</personal>
	<title>
		<profession>Software Developer</profession>
		<presentation>
			Passionate about Software development, I've been practicing this discipline for ten years. Curious, I can work on various fields : front-end, back-end, architecture, methodology, system administration.
			<newline/>
            Looking for better tools and better ways to be more efficient, I like to learn, exchange, and work with other passionate professionals.
		</presentation>
	</title>
	<educations>
		<education abstract="true">
			<year>2007</year>
			<certificate>Master of Engineering in Computer Sciences</certificate>
			<speciality>Computer Networks</speciality>
			<school>
				<title>Polytech'Grenoble</title>
				<www>www.polytech-grenoble.fr</www>
			</school>
		</education>
		<education>
			<year>2004</year>
			<certificate>Bachelor's Degree in Computer Sciences</certificate>
			<school>
				<title>Joseph Fourier’s University</title>
				<www>www.ujf-grenoble.fr</www>
				<city>Grenoble</city>
			</school>
		</education>
	</educations>
	<trainings>
		<training abstract="true">
			<year>2015</year>
			<title>AngularJs</title>
			<organization>
				<title>MethoTIC Conseil</title>
				<www>http://www.methotic.com/formation-angularjs</www>
			</organization>
		</training>
		<training abstract="true">
			<year>2014</year>
			<title>Oracle Certified Professional, Java SE 6 Programmer</title>
			<organization>
				<title>Oracle</title>
				<www>http://lc.cx/ZLkd</www>
			</organization>
		</training>
		<training>
			<year>2011</year>
			<title>Java optimisation</title>
			<organization>
				<title>Bull Formation</title>
			</organization>
		</training>
		<training>
			<year>2010</year>
			<title>Web services</title>
			<organization>
				<title>Bull Formation</title>
			</organization>
		</training>
	</trainings>
	<experiences>
		<experience abstract="true">
			<year>Since 2016</year>
			<title>Software engineer</title>
			<company>
				<title>Leadformance</title>
				<www>https://www.leadformance.com/</www>
			</company>
			<description>
				Maintenance of Ruby on Rails application BRIDGEv2. <newline />
				Development of the new version BRIDGEv3 based on Microservices architecture written in NodeJS/AngularJS and deployed using Docker/Kubernetes in AWS cloud.<newline />
				<underline>Achievements Highlights</underline>
				<list>
					<item>Implementation of the SSO solution using Keycloak</item>
					<item>Development of Presence Management features of BRIDGE (GMB, Pages Jaunes, ...)</item>
                    <item>Setting up and maintaining Jenkins CI</item>
                    <item>Technical leader</item>
				</list>
				<underline>Environment</underline>
				<list>
					<item>4 SCRUM teams (2 to 5 members)</item>
					<item>Dev skills: Ruby on Rails, NodeJS, TypeScript, Angular, Git, Cucumber</item>
					<item>Ops skills: AWS, Docker, Kubernetes, Puppet</item>
				</list>
			</description>
			<missions>
				<mission>
					<title>Maintenance BRIDGE V2 application</title>
					<competences>Ruby on Rails, Git, Puppet, Postgres, AWS</competences>
				</mission>
				<mission>
					<title>Development of the new version BRIDGE V3</title>
					<competences>NodeJS, Symfony, AngularJS, Git, Cucumber, Docker, Kubernetes, AWS</competences>
					<detail>
						Rewrite of BRIDGE application based on Microservices architecture written in NodeJS/AngularJS and deployed using Docker/Kubernetes in AWS cloud
					</detail>
				</mission>
			</missions>
		</experience>
		<experience abstract="true">
			<year>2007 - 2016</year>
			<title>Software engineer</title>
			<company>
				<title>Bull</title>
				<www>www.bull.com</www>
			</company>
			<description>
				Provide object-oriented software design for different government agencies (Pôle Emploi, Conseil d'Etat, ONIAM) with different technologies. <newline />
				<underline>Achievements Highlights</underline>
				<list>
					<item>Software architecture and design</item>
					<item>Software development</item>
					<item>Technical leader</item>
					<item>Responsible for setting up XP methodologies : countinuous integration, automated tests, TDD</item>
				</list>
				<underline>Environment</underline>
				<list>
					<item>Agile team of 4 to 6 people with SCRUM</item>
					<item>Skills : Java, Javascript, HTML5/CSS3, Subversion, Git, Maven, Weblogic</item>
					<item>Frameworks : Spring, Jersey, Axis2, Tapestry5, AngularJS</item>
				</list>
			</description>
			<missions>
				<mission>
					<title>Framework PN NG</title>
					<competences>AngularJS, Javascript, REST, GulpJS</competences>
					<responsibility>Architecture, design, development, advisory missions</responsibility>
					<detail>
						Pole Emploi offers a new technical stack for software development based on AngularJS.
						<newline/>
						Mission dealt with
						<list>
							<item>best practices definition for software development with AngularJS</item>
							<item>implementation of commons services for applications (log management, metrology, authentication, ...)
							</item>
						</list>
					</detail>
				</mission>
				<mission>
					<title>IDFIX</title>
					<competences>REST, Java, Spring, Jersey, Maven, Weblogic</competences>
					<responsibility>Architecture, design, development, tests</responsibility>
					<detail>
						GUI to administrate applications built on Pôle Emploi internal framework. IDFIX allows people to update the configuration without reloading applications.
						<newline/>
						Applications subscribe to an administration service when they start. This service allows IDFIX to
						<list>
							<item>notify each cluster members of an application with the new configuration.</item>
							<item>flush out application cache.</item>
						</list>
					</detail>
				</mission>
				<mission>
					<title>Bureau Métier</title>
					<competences>Java, Spring, HTML/CSS, EHCache, Javascript (Prototype, Liveconnect), Maven, Weblogic</competences>
					<responsibility>Architecture, design, development, tests</responsibility>
					<detail>
						Bureau Métier is a portal allowing Pôle Emploi agents to access to their applications. This portal is used daily by 45,000 agents. Features provided by this portal :
						<list>
							<item>show to agents only their authorized applications.</item>
							<item>handle the application startup using different versions of the Pôle Emploi internal framework.</item>
							<item>provide printing functionality for all applications launched by the portal.</item>
							<item>handle an inter-applications link in order to hide the user the applications switch when he achieves core operational activities.
							</item>
						</list>
					</detail>
				</mission>
				<mission>
					<title>Notification server DISI.</title>
					<competences>Java, Spring, HTML/CSS, Maven, Weblogic</competences>
					<responsibility>Architecture, design, development, tests</responsibility>
					<detail>
						Notification server receives alerts on the Information System state to spread them on agents computers. This allows agents to be warned about malfunctions of the Information System in order to unblock the help desk.
					</detail>
				</mission>
				<mission>
					<title>Frontal Annuaire</title>
					<competences>Java, Spring, Axis2, Maven, Weblogic</competences>
					<responsibility>Architecture, design, development, tests</responsibility>
					<detail>
						Server composed of severals webservices allowing Pôle Emploi LDAP directories management. These webservices
						<list>
							<item>allow the 45,000 Pôle Emploi agents to authenticate</item>
							<item>provide a centralized access to LDAP directories for others applications</item>
							<item>allow directories management tasks automation (new agent creation, removal, transfert of an agent to another agency...)
							</item>
						</list>
					</detail>
				</mission>
				<mission>
					<title>Framework PN V4</title>
					<competences>Java, Spring, JSF, AspectJ, EHCache, HTML/CSS, Javascript, Maven, Weblogic</competences>
					<responsibility>Design, development, tests</responsibility>
					<detail>
						PNSLD framework (Presentation Navigation Services Logic and Data) has been created to simplify softwares development by inexperienced people. This framework allows developers to build applications used by the 45,000 agents.
						This mission dealt on the rewritting of presentation and navigation layers of the framework :
						<list>
							<item>
								Navigation layer provides an engine to link different states of an application. This layer communicates with the second part of the framework (SLD).
							</item>
							<item>
								Presentation layer, based on JSF, allows developers to design user interface. Graphical components (tree view, lists, histograms, ...) are available to make developers job easier.
							</item>
						</list>
					</detail>
				</mission>
				<mission>
					<title>Maintenance of the DGME application : Subventions en ligne.</title>
					<competences>Java, HTML, PostgreSQL, Yourkit</competences>
